[vps]
ru-vps-main ansible_host=45.131.41.34
la-vps ansible_host=5.189.254.175

[home]
sh-homelab ansible_host=10.10.30.165

[android]
# ssh -p 8022 u0_a226@10.10.20.14
# cd /data/data/com.termux/files/home/storage/shared/backup-storage
seeker ansible_host=10.10.20.14 ansible_port=8022