node_exporter_url: "http://10.10.30.165:9004/EXPOFORUM/s3/raw/branch/main/node_exporter"
node_exporter_path: "/opt/node_exporter"
node_exporter_port: "9100"
service_file_path: "/etc/systemd/system/node_exporter.service"
service_user: service_ansible

bin_path: "{{ node_exporter_path }}/node_exporter"
