---

# Скопируй этот файл, переименуй в <hostname>.yml
# Имя файла должно совпадать с именем хоста в inventory

# идеи на будущее 
# для каждого сервера создавать список админов, которым можно туда ходить

- name: Setup <hostname>
  hosts: <hostname>
  gather_facts: true
  ignore_unreachable: true
  become: true
  vars:
    # Переменные для ролей — перебивают defaults роли
    #
    # node_exporter_url: ""
    # prom_url: ""

  roles:
    # Порядок важен — роли выполняются сверху вниз
    #
    - preflight
    # - node_exporter
    # - prometheus
