---

- name: Common setup
  hosts: "{{ target | mandatory('Укажи target в Extra Variables: all, имя группы или хоста') }}"
  gather_facts: true
  become: true
  vars:
  roles:
    - preflight
    - service_user
    - server_info
