- include_tasks: os.yml
- include_tasks: dns.yml

- name: info | output
  debug:
    msg:
      - "=== {{ inventory_hostname }} ==="
      - "OS:           {{ info_os }}"
      - "DNS manager:  {{ info_dns_manager | trim }}"
      - "Nameservers:  {{ info_dns_nameservers }}"
