---

- name: Write /etc/resolv.conf
  copy:
    dest: /etc/resolv.conf
    content: |
      {% for srv in dns_servers %}
      nameserver {{ srv }}
      {% endfor %}
      {% if dns_domain %}
      search {{ dns_domain }}
      {% endif %}
    mode: "0644"
