- name: Setup server_2
  hosts: server_2
  become: true
  vars:
    nftables_ports:
      - 22
      - 80
      - 443
      - 8080
    nginx_server_name: app.example.com
    nginx_proxy_pass: http://localhost:3000
  tasks:
    - include_tasks: roles/nftables.yml
    - include_tasks: roles/nginx.yml
  handlers:
    - name: Reload nftables        # ↓ эти три строки
      service:                     #   придётся копировать
        name: nftables             #   в каждый сервер
        state: reloaded            #   где есть nftables
    - name: Reload nginx           # ↓ и эти три строки
      service:                     #   придётся копировать
        name: nginx                #   в каждый сервер
        state: reloaded            #   где есть nginx
