- name: Setup server_2
  hosts: server_2
  become: true
  vars:
    nftables_ports:
      - 22
      - 80
      - 443
      - 8080
    nginx_server_name: app.example.com
    nginx_proxy_pass: http://localhost:3000
  tasks:
    - include_tasks: roles/nftables.yml
    - include_tasks: roles/nginx.yml
