---

- name: Server init
  hosts: "{{ target }}"
  gather_facts: true
  become: true
  roles:
    - preflight
    - server_init


# ручное тестирование ssh
# ssh -o PreferredAuthentications=password user@host